services:
  presto_x728:
    image: presto_x728
    container_name: presto_x728
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    #privileged: true
    user: "0:0"  # Run as root for device access
    
    group_add:
      - 994 # Host i2c group GID
      - 993 # Host gpio group GID
    
    network_mode: host
    
    cap_add:
      - SYS_RAWIO
      - NET_BIND_SERVICE
      - ALL
    volumes:
      - /dev:/dev
      #- /run/systemd:/run/systemd
      - /sys:/sys:ro
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:ro
      - /proc/uptime:/proc/uptime
      #- /sbin:/sbin  # Mount host's shutdown binary
      #- /usr/sbin:/usr/sbin  # Mount for DietPi/RetroPie compatibility
      #- /bin:/bin  # For RetroPie/edge cases
      - /:/host:ro
      - ./volumes/presto_x728/config:/config
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip4:/dev/gpiochip4
      - /dev/i2c-1:/dev/i2c-1
    restart: unless-stopped
    pid: host
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "1", "--worker-class", "gevent", "--timeout", "120", "presto_x728:app"]
